version: '3.1'

services:

  service:
    container_name: kanban
    image: kanban
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017